apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pihole-etc-pv
  storageClassName: ""
